---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/component: sonar

resources:
- sonar-namespace.yaml
- postgres/postgres-pvc.yaml
- sonar/sonar-pvc.yaml
- postgres/postgres-app.yaml
- sonar/sonar-app.yaml
- sonar/sonar-ingress.yaml

patches:
# yep.. you should add your own and secure secrets within an overlay
  - path: delete-secret.yaml
    target: 
      kind: Secret
  - target:
      kind: Deployment
      name: sonar
    patch: |-
# you should configure your host, instead of doing it with the init container... you do not want to make the namespace privileged, really..
      - op: remove
        path: /spec/template/spec/initContainers
# fix for elasticsearch usage with sonarqube:10.7.0-community and persistent volume
      - op: add
        path: /spec/template/spec/securityContext
        value: {fsGroup: 1000}
# to update the image without changing the base, if you like
#      - op: replace
#        path: /spec/template/spec/containers/0/image
#        value: "sonarqube:10.7.0-community"
