---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  app.kubernetes.io/component: sonar

resources:
- sonar-namespace.yaml
- postgres/postgres-pvc.yaml
- sonar/sonar-pvc.yaml
- postgres/postgres-app.yaml
- sonar/sonar-app.yaml
- sonar/sonar-ingress.yaml