---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  app.kubernetes.io/component: sonar

resources:
- sonar-namespace.yaml
- postgres-pvc.yaml
- sonar-pvc.yaml
- postgres-app.yaml
- sonar-app.yaml
- sonar-ingress.yaml